### PR TITLE
Customise the number of connections to each host

### PR DESCRIPTION
**Pull request by gouthamve**
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>

### CODE REVIEW

**Comment by Dieterbe** [comment]
> Still need to test it out.

i'll wait for further news then before merging ?

**Comment by gouthamve** [comment]
screen shot 2018-10-23 at 12 44 25

The graph for the last 6 hours. The latency dropped quite a lot after the latest deploy. While the general 5xx have reduced (nothing in the last `1h`), we do have sporadic spikes with a new error:
```
2018/10/23 16:42:58 http: proxy error: EOF
2018/10/23 16:42:58 http: proxy error: EOF
```

**Comment by gouthamve** [comment]
Hmm, irrespective of the new error, I think this should be merged. It's much more stable now. And the latency is muuuuch better. I'll open another PR for the error detected.

**Comment by gouthamve** [comment]
This is causing super bad load-balancing for us though.

See this blog by Tom: https://www.weave.works/blog/turtles-way-http-grpc/

> We disabled persistent connections in AuthFE to downstream services as the combination of Go’s HTTP client and kubeproxy meant we weren’t getting good load balancing. This was quite critical for Scope’s query performance, as Scope queries are implausibly CPU intensive.

**Pull request merged**
